
version: '3.8'

services:
  # todo:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - node_modules:/todo/node_modules
  api:
    image: todo
    healthcheck:
      test: ["CMD",  "node", "./apps/api-todo/health-check.js"]
      interval: 3s
      timeout: 10s
      retries: 3
    depends_on:
      - serviceName
    volumes:
      - node_modules:/todo/node_modules
    ports:
      - 4200:4200

  test:
    image: todo
    command: yarn test api-todo
    volumes:
      - node_modules:/todo/node_modules
    environment:
      APP_ENV: 'docker'
    depends_on:
      api: 
        condition: service_healthy

volumes:
  node_modules: