
version: '3.8'

services:
  api:
    image: todo
    healthcheck:
      test: ["CMD",  "node", "./apps/api-todo/health-check.js"]
      interval: 3s
      timeout: 10s
      retries: 3
    command: yarn start api-todo
    env_file: .env
    volumes:
      - .:/todo/
      - node_modules:/todo/node_modules
    ports:
      - 8080:8080
  
  api-unit:
    image: todo
    command: yarn test api-todo
    env_file: .env
    volumes:
      - .:/todo/
      - node_modules:/todo/node_modules

  app:
    image: todo
    healthcheck:
      test: ["CMD",  "node", "./apps/app-todo/health-check.js"]
      interval: 3s
      timeout: 10s
      retries: 3
    command: yarn start app-todo
    depends_on:
      api:
        condition: service_healthy
    env_file: .env
    volumes:
      - .:/todo/
      - node_modules:/todo/node_modules
    ports:
      - 4200:4200
volumes:
  node_modules: