
version: '3.8'

services:
  api:
    image: todo
    container_name: api-todo
    healthcheck:
      test: ["CMD",  "curl", "http://localhost:3001"]
      interval: 3s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks: 
      - todo-net
    command: yarn start api-todo
    env_file: .env
    volumes:
      - .:/todo/
      - node_modules:/todo/node_modules
    ports:
      - "3001:3001"
  
  api-unit:
    image: todo
    container_name: api-unit
    command: yarn test api-todo
    env_file: .env
    networks: 
      - todo-net
    volumes:
      - .:/todo/
      - node_modules:/todo/node_modules

  api-int:
    image: todo
    container_name: api-int
    command: yarn nx run api-todo:test-int
    env_file: .env
    networks: 
      - todo-net
    depends_on:
      api:
        condition: service_healthy
    volumes:
      - .:/todo/
      - node_modules:/todo/node_modules

  app:
    image: todo
    container_name: app-todo
    healthcheck:
      test: ["CMD",  "curl", "http://localhost:3000"]
      interval: 3s
      timeout: 10s
      retries: 3
      start_period: 1m
    networks: 
      - todo-net
    command: yarn start app-todo --host 0.0.0.0
    depends_on:
      api:
        condition: service_healthy
    env_file: .env
    volumes:
      - .:/todo/
      - node_modules:/todo/node_modules
    ports:
      - "3000:3000"

  app-e2e:
    image: cypress/included:9.6.1
    container_name: app-e2e
    command: yarn nx run app-todo-e2e:e2e
    working_dir: /todo/
    networks: 
      - todo-net
    entrypoint: []
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - ./:/todo/
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - node_modules:/todo/node_modules
    environment:
      DISPLAY: $DISPLAY

networks:
  todo-net:
volumes:
  node_modules: